import { Adele_Hello, Adele_SomeoneLikeYou, Drake_LaughNowCryLater, ImagineDragons_FollowYou, ImagineDragons_Natural, LanaDelRey_BornToDie, LanaDelRey_YoungAndBeautiful, Madonna_Frozen, TheWeeknd_SaveYourTears, TomOdell_AnotherLove, TomOdell_CantPretend, ToveLo_HowLong } from "./audioTracksList";

export const dataMusic = [
    {
      id: '1',
      artist: 'The Weeknd',
      track: 'Save your tears',
      poster: 'img/photo1.jpg',
      mp3: TheWeeknd_SaveYourTears,
    },
    {
      id: '2',
      artist: 'Imagine Dragons',
      track: 'Follow You',
      poster: 'img/photo2.jpg',
      mp3: ImagineDragons_FollowYou,
    },
    {
      id: '3',
      artist: 'Tove Lo',
      track: 'How Long',
      poster: 'img/photo3.jpg',
      mp3: ToveLo_HowLong,
    },
    {
      id: '4',
      artist: 'Tom Odell',
      track: 'Another Love',
      poster: 'img/photo4.jpg',
      mp3: TomOdell_AnotherLove,
    },
    {
      id: '5',
      artist: 'Lana Del Rey',
      track: 'Born To Die',
      poster: 'img/photo5.jpg',
      mp3: LanaDelRey_BornToDie,
    },
    {
      id: '6',
      artist: 'Adele',
      track: 'Hello',
      poster: 'img/photo6.jpg',
      mp3: Adele_Hello,
    },
    {
      id: '7',
      artist: 'Tom Odell',
      track: "Can't Pretend",
      poster: 'img/photo7.jpg',
      mp3: TomOdell_CantPretend,
    },
    {
      id: '8',
      artist: 'Lana Del Rey',
      track: 'Young And Beautiful',
      poster: 'img/photo8.jpg',
      mp3: LanaDelRey_YoungAndBeautiful,
    },
    {
      id: '9',
      artist: 'Adele',
      track: 'Someone Like You',
      poster: 'img/photo9.jpg',
      mp3:  Adele_SomeoneLikeYou,
    },
    {
      id: '10',
      artist: 'Imagine Dragons',
      track: 'Natural',
      poster: 'img/photo10.jpg',
      mp3: ImagineDragons_Natural,
    },
    {
      id: '11',
      artist: 'Drake',
      track: 'Laugh Now Cry Later',
      poster: 'img/photo11.jpg',
      mp3: Drake_LaughNowCryLater,
    },
    {
      id: '12',
      artist: 'Madonna',
      track: 'Frozen',
      poster: 'img/photo12.jpg',
      mp3: Madonna_Frozen,
    },
  ];